// ~300 GenLayer trivia questions, randomly picked on each page load.

export const QUESTIONS: string[] = [
  // ── Consensus Mechanism ──
  'What consensus mechanism does GenLayer use?',
  'How does Optimistic Democracy differ from traditional BFT consensus?',
  'Why is GenLayer\'s consensus called "optimistic"?',
  'What role do LLMs play in GenLayer\'s consensus process?',
  'How many validators are required per transaction by default in GenLayer?',
  'What happens when validators disagree on a transaction outcome?',
  'How does GenLayer handle non-deterministic operations in consensus?',
  'What is the commit-reveal scheme used for in GenLayer consensus?',
  'Why do GenLayer validators run different LLMs?',
  'What is the purpose of the Equivalence Principle in GenLayer?',
  'How does GenLayer prevent vote manipulation during consensus?',
  'What is the role of the leader validator in GenLayer consensus?',
  'How are validator votes weighted in GenLayer?',
  'What happens if the leader validator times out?',
  'How does GenLayer achieve Byzantine fault tolerance?',
  'What is the maximum number of appeal rounds in GenLayer?',
  'How does the appeal process expand the validator set?',
  'What is the difference between accepted and finalized transactions in GenLayer?',
  'How does GenLayer\'s consensus handle LLM output variability?',
  'What is a consensus round in GenLayer?',

  // ── Intelligent Contracts ──
  'What are Intelligent Contracts in GenLayer?',
  'How do Intelligent Contracts differ from traditional smart contracts?',
  'What programming language is used to write GenLayer Intelligent Contracts?',
  'Can Intelligent Contracts access real-time web data?',
  'How do Intelligent Contracts process natural language?',
  'What is the GenVM and what does it execute?',
  'What makes Intelligent Contracts "intelligent"?',
  'Can Intelligent Contracts make HTTP requests to external APIs?',
  'How do Intelligent Contracts use LLMs during execution?',
  'What types of applications can be built with Intelligent Contracts?',
  'How are Intelligent Contracts deployed on GenLayer?',
  'What is the role of the @gl.public.write decorator?',
  'What is the role of the @gl.public.view decorator?',
  'What is the difference between view and write methods in Intelligent Contracts?',
  'How do Intelligent Contracts handle state persistence?',
  'What storage types are available in GenLayer Intelligent Contracts?',
  'What is a TreeMap in GenLayer storage?',
  'What is a DynArray in GenLayer storage?',
  'Why can\'t you use Python dict or list for contract storage?',
  'What is the u256 type used for in GenLayer?',
  'How do you declare storage fields in an Intelligent Contract?',
  'What is the gl.Contract base class?',
  'How does the __init__ method work in Intelligent Contracts?',
  'What is gl.message.sender_address?',
  'How do Intelligent Contracts handle errors?',
  'What is gl.vm.UserError used for?',
  'What is the purpose of the contract header comment in GenLayer?',
  'How do you fund an Intelligent Contract with native tokens?',
  'What is the @gl.public.write.payable decorator for?',
  'Can Intelligent Contracts deploy other contracts?',
  'What is the factory pattern in GenLayer contracts?',

  // ── Equivalence Principle ──
  'What is the Equivalence Principle in GenLayer?',
  'When should you use strict_eq in GenLayer?',
  'When should you use a custom validator function instead of strict_eq?',
  'What is gl.eq_principle.strict_eq used for?',
  'What is gl.vm.run_nondet_unsafe used for?',
  'What is prompt_comparative in GenLayer?',
  'What is prompt_non_comparative in GenLayer?',
  'Why should you never use strict_eq for LLM calls?',
  'How do custom validator functions work in GenLayer?',
  'What does the validator function receive as its argument?',
  'How should validators handle leader errors?',
  'What is the difference between deterministic and non-deterministic operations?',
  'How do you implement tolerance-based comparison in a validator function?',
  'What happens when a validator function returns False?',
  'What happens when a validator function returns True?',
  'How should you handle LLM response variability in validator functions?',
  'What is the leader function in GenLayer\'s nondet pattern?',
  'Can validators re-execute the leader function?',
  'How do you extract stable fields for consensus comparison?',
  'What is the purpose of error classification in GenLayer contracts?',

  // ── Validators & Staking ──
  'What is the role of validators in GenLayer?',
  'How do validators participate in GenLayer consensus?',
  'What must validators stake to participate in GenLayer?',
  'How are validators selected for transactions?',
  'What is stake-weighted selection in GenLayer?',
  'What is the minimum number of validators per transaction?',
  'How does the validator selection use VRF?',
  'What is an activator in GenLayer?',
  'How are activators chosen in GenLayer?',
  'What happens when a validator is idle or unresponsive?',
  'What is the quarantine system in GenLayer?',
  'How does slashing work in GenLayer?',
  'What is the difference between a validator and a delegator in GenLayer?',
  'Can an address be both a validator and delegator simultaneously?',
  'What is the epoch system in GenLayer staking?',
  'How does the unbonding period work for validators?',
  'What is validator priming in GenLayer?',
  'How does GenLayer handle validator misbehavior?',
  'What is the maximum number of validators supported by GenLayer?',
  'How does inflation distribution work in GenLayer?',
  'What percentage of inflation goes to stakers in GenLayer?',
  'What is the initial inflation rate in GenLayer?',
  'What is the final target inflation rate in GenLayer?',
  'How does the binary tree structure organize validators?',
  'What is the dual stake record (X/Y) pattern?',
  'How does the commit/claim pattern work in staking?',
  'What is a ValidatorWallet in GenLayer?',
  'What is the difference between a validator owner and operator?',
  'How does the ValidatorWalletFactory work?',
  'What is the BeaconProxy pattern used for in GenLayer?',

  // ── Transaction Lifecycle ──
  'What are the stages of a transaction in GenLayer?',
  'What happens during the Pending stage of a transaction?',
  'What happens during the Proposing stage?',
  'What happens during the Committing stage?',
  'What happens during the Revealing stage?',
  'What does it mean when a transaction is Accepted?',
  'What does it mean when a transaction is Finalized?',
  'Can a finalized transaction be reversed?',
  'What triggers the appeal window for a transaction?',
  'How long is the appeal window in GenLayer?',
  'What is the difference between Accepted and Finalized status?',
  'What happens during the Leader Revealing stage?',
  'What is the Decided state and its substates?',
  'What causes a LeaderTimeout substate?',
  'What causes a ValidatorTimeout substate?',
  'What is the Undetermined substate?',
  'How does leader rotation work during transactions?',
  'What happens when a transaction enters the Appeal state?',
  'How many validators are added per appeal round?',
  'What is the maximum number of appeal rounds allowed?',

  // ── Web Data & External Access ──
  'How do Intelligent Contracts access web data?',
  'What is gl.nondet.web.get used for?',
  'What is gl.nondet.web.post used for?',
  'Why are web requests non-deterministic in GenLayer?',
  'How do you handle API responses in Intelligent Contracts?',
  'What is the difference between deterministic and non-deterministic web calls?',
  'How should you handle HTTP errors in contract web requests?',
  'What is the purpose of error prefixes like [EXTERNAL] and [TRANSIENT]?',
  'How do you extract stable fields from variable API responses?',
  'Can Intelligent Contracts verify data from other blockchains?',
  'How does cross-chain RPC verification work in GenLayer?',
  'What web request modes are available in GenLayer?',
  'How do you handle rate-limited APIs in Intelligent Contracts?',
  'What happens if a web request fails during consensus?',
  'How should transient errors be classified for consensus?',
  'What is the difference between [EXPECTED] and [TRANSIENT] errors?',
  'How do validators compare web request results?',
  'Can Intelligent Contracts scrape web pages?',
  'What is gl.get_webpage used for?',
  'How do you handle JSON parsing from web responses?',

  // ── LLM Integration ──
  'How do Intelligent Contracts call LLMs?',
  'What is gl.nondet.exec_prompt used for?',
  'What is the response_format parameter in exec_prompt?',
  'Why should you always use response_format="json" with LLM calls?',
  'How do you handle unpredictable LLM output formats?',
  'What is key aliasing when parsing LLM responses?',
  'How should you defensively parse LLM JSON responses?',
  'What happens when an LLM returns an invalid response?',
  'How should LLM errors be classified for consensus?',
  'What is the [LLM_ERROR] prefix used for?',
  'Why should validators disagree on LLM errors?',
  'How do you clean up malformed JSON from LLM output?',
  'Can different validators get different LLM responses?',
  'How does GenLayer handle LLM non-determinism across validators?',
  'What strategies exist for comparing LLM outputs between leader and validators?',
  'How do you implement grade tolerance in LLM-based contracts?',
  'What is the role of the LLM in the Trivia Faucet contract?',
  'How does the Trivia Faucet grade answers from 1 to 5?',
  'What happens if the LLM returns a grade outside the 1-5 range?',
  'How do you coerce LLM output to the expected numeric type?',

  // ── Cross-Contract Interaction ──
  'How do Intelligent Contracts interact with each other?',
  'What is gl.get_contract_at used for?',
  'How do you read from another contract synchronously?',
  'How do you write to another contract asynchronously?',
  'What is the emit() method on a contract proxy?',
  'What is the emit_transfer() method used for?',
  'What is the difference between on="accepted" and on="finalized" messages?',
  'When should you use on="accepted" for cross-contract messages?',
  'When should you use on="finalized" for cross-contract messages?',
  'What happens to emitted messages if a transaction is appealed?',
  'How does the factory pattern deploy child contracts?',
  'What is gl.deploy_contract used for?',
  'Can you update a deployed Intelligent Contract?',
  'What is the salt_nonce parameter in deploy_contract?',
  'How do cross-contract view calls work?',

  // ── Fees & Economics ──
  'How are transaction fees calculated in GenLayer?',
  'What is pay-for-performance in GenLayer\'s fee system?',
  'How do appeal bonds work in GenLayer?',
  'What happens to fees when a leader times out?',
  'How are fees distributed to validators?',
  'Do validators who vote against the outcome receive fees?',
  'How are unused fees handled in GenLayer?',
  'What happens to appeal bonds after a successful appeal?',
  'What happens to appeal bonds after a failed appeal?',
  'How does fee pre-calculation work in GenLayer?',
  'What is the GEN token used for in GenLayer?',
  'How does GenLayer\'s native token economy work?',
  'What is the atto scale (10^18) used for in GenLayer?',
  'Why should money values use u256 instead of float?',
  'How does the FeeManager contract work?',

  // ── Architecture & Infrastructure ──
  'What is GenLayer\'s relationship to zkSync?',
  'What is the rollup architecture in GenLayer?',
  'What are ghost contracts in GenLayer?',
  'What is the GhostFactory used for?',
  'What is the GhostBlueprint?',
  'What is the GhostManager?',
  'How does the message passing system work between contracts?',
  'What is the ConsensusMain contract responsible for?',
  'What is the ConsensusManager?',
  'What is the ConsensusData contract?',
  'What is the Transactions contract?',
  'What is the Rounds contract?',
  'What is the Voting contract?',
  'What is the Idleness contract?',
  'What is the TribunalAppeal contract?',
  'What is the Queues contract used for?',
  'How does GenLayer use the upgradeable proxy pattern?',
  'What is the role of the Messages contract?',
  'How does GenLayer handle contract upgrades?',
  'What is the diamond pattern used in GenLayer staking?',

  // ── Development & Tools ──
  'What tools are needed to develop GenLayer Intelligent Contracts?',
  'What is the GenLayer CLI used for?',
  'How do you deploy a contract using the GenLayer CLI?',
  'How do you call a view method using the CLI?',
  'How do you send a write transaction using the CLI?',
  'What is genvm-lint used for?',
  'How do you validate an Intelligent Contract before deployment?',
  'What is GenLayer Studio?',
  'How do you run a local GenLayer development environment?',
  'What is the genlayer-js SDK?',
  'How do you create a client with genlayer-js?',
  'What is the readContract method in genlayer-js?',
  'What is the writeContract method in genlayer-js?',
  'How do you wait for transaction receipt in genlayer-js?',
  'What is the createAccount function in genlayer-js?',
  'How do you configure the GenLayer network in the CLI?',
  'What networks are available in GenLayer (localnet, testnet, etc.)?',
  'What is Testnet Bradbury?',
  'How do you get testnet GEN tokens?',
  'What is the GenLayer Explorer used for?',

  // ── Testing ──
  'How do you test GenLayer Intelligent Contracts?',
  'What is direct mode testing in GenLayer?',
  'How fast are direct mode tests?',
  'What fixtures are available in direct mode tests?',
  'How do you mock web requests in direct mode tests?',
  'How do you mock LLM responses in direct mode tests?',
  'What is direct_vm used for in tests?',
  'What is direct_deploy used for in tests?',
  'How do you test access control in Intelligent Contracts?',
  'How do you test state transitions in Intelligent Contracts?',
  'What is direct_vm.expect_revert used for?',
  'How do you set the transaction sender in tests?',
  'What is the prank function in direct_vm?',
  'How do you test with native value (msg.value) in direct mode?',
  'What is the difference between direct mode and integration tests?',
  'How do you snapshot and restore state in tests?',
  'What is direct_vm.deal used for?',
  'What is direct_vm.warp used for?',
  'How do you clear mocks between test scenarios?',
  'What should you test in direct mode vs integration mode?',

  // ── Security ──
  'How does GenLayer achieve Sybil resistance?',
  'What is VRF-based randomness used for in GenLayer?',
  'How does economic security work in GenLayer?',
  'What is the Byzantine fault tolerance threshold in GenLayer?',
  'How does GenLayer prevent frontrunning?',
  'What security guarantees does commit-reveal provide?',
  'How does GenLayer handle malicious validators?',
  'What is the slashing mechanism for in GenLayer?',
  'How does the quarantine system protect the network?',
  'What security considerations apply to Intelligent Contract development?',
  'How do you prevent reentrancy in Intelligent Contracts?',
  'What is the role of access control in Intelligent Contracts?',
  'How do you safely handle user input in Intelligent Contracts?',
  'What are common anti-patterns in Intelligent Contract development?',
  'Why should you not store Enum types directly in contract storage?',

  // ── Use Cases ──
  'What are some example use cases for GenLayer Intelligent Contracts?',
  'How could GenLayer be used for AI-driven DAOs?',
  'How could GenLayer enable dynamic pricing systems?',
  'How could GenLayer handle automated dispute resolution?',
  'What is an intelligent oracle in GenLayer?',
  'How does GenLayer differ from traditional oracle solutions like Chainlink?',
  'Could GenLayer contracts analyze sentiment from social media?',
  'How could Intelligent Contracts verify real-world events?',
  'What types of prediction markets could GenLayer enable?',
  'How could GenLayer be used for content moderation?',
  'What is a Trivia Faucet and how does it work?',
  'How could Intelligent Contracts power insurance claim processing?',
  'Could GenLayer contracts analyze financial data in real-time?',
  'How might Intelligent Contracts be used for supply chain verification?',
  'What advantages do Intelligent Contracts have over traditional smart contracts for DeFi?',

  // ── GenLayer Platform ──
  'What blockchain platform is GenLayer built on?',
  'What is the native token of GenLayer?',
  'What is the GenLayer testnet called?',
  'How does GenLayer integrate AI at the protocol level?',
  'What makes GenLayer different from other L2 solutions?',
  'How does GenLayer eliminate the need for external oracles?',
  'What is the GenLayer SDK?',
  'What programming paradigm do Intelligent Contracts follow?',
  'How does GenLayer handle contract state persistence?',
  'What is the GenLayer Foundation?',
  'How does GenLayer handle network upgrades?',
  'What is the GenLayer whitepaper about?',
  'How does GenLayer compare to traditional EVM-based blockchains?',
  'What is the GenLayer faucet and how do you use it?',
  'What documentation resources are available for GenLayer developers?',

  // ── Storage & Data ──
  'What storage types does GenLayer support for contracts?',
  'How does TreeMap work in GenLayer storage?',
  'How does DynArray work in GenLayer storage?',
  'What is the Address type in GenLayer?',
  'How do you use dataclasses for complex state in GenLayer?',
  'What is the @allow_storage decorator?',
  'Why must new storage fields be appended at the end?',
  'How do you handle default values for new storage fields?',
  'What is the O(1) stat index pattern in GenLayer?',
  'How should you initialize DynArray and TreeMap in __init__?',
  'Can you use float for money in Intelligent Contracts?',
  'What is atto-scale (10^18) and why is it used?',
  'How does storage layout affect upgradeable contracts?',
  'What types are not allowed in GenLayer contract storage?',
  'How do you store enum values in GenLayer contracts?',
];

export function getRandomQuestion(): string {
  return QUESTIONS[Math.floor(Math.random() * QUESTIONS.length)];
}
